# Azure Pipelines for Utilities.Billing.Api using shared template

trigger:
- develop
- master

resources:
  repositories:
  - repository: self
  - repository: ai_pipelines
    type: github
    endpoint: dmitrynadolin
    name: dmitrynadolin/ai-pipelines
    ref: develop
  - repository: backend_configs
    type: github
    endpoint: dmitrynadolin
    name: UMEC-Corp/backend-configs
    ref: develop

extends:
  template: /build/azure-pipelines-template.yml@backend_configs
  parameters:
    serviceName: 'utilities-billing'
    dockerfile: 'Utilities.Billing.Api/Dockerfile'