netcore-service:
  image:
    repository: deviot.azurecr.io/utilities-billing
    # Overrides the image tag whose default is the chart appVersion.
    tag: "latest"

  imagePullSecrets:
    - name: regcred-deviot

  environment: "Production"

  consulUrl: "common-services-consul-headless.umec-production.svc.cluster.local:8500"

  grpc:
    host: "grpc-billing.umec.deviot.cloud"
    targetPort: 81
    tls:
      secretName: "wc-deviot-cloud-crt-secret"

  probes:
    enabled: true

postgresql:
  enabled: false

